---
title: "Machine Learning Harvard Capstone Movie Lens Project R Notebook"
output: html_notebook
---

### Machine Learning Harvard Capstone Movie Lens Project R Notebook

June 2019

This is my Move Lens project for the Capstone Course in the HarvardX Data Science Certificate Program.

Student: Philip Brown
email: Phil@pjb3.com
github: https://github.com/pjbMit

The project was created in the RStudio environment 
using Rstudio Version 1.1.442 
on a Macintosh; Intel Mac OS X 10_14_5

R version 3.5.1 (2018-07-02)  
nickname       Feather Spray

See the README.Rmd or README.html files for more information on the environment and setup.

For questions, email me:   pjbMit@pjb3.com  , and I'll gladly respond promptly.


---------------------------
1) Develop your algorithm using the edx set. 

2) For a final test of your algorithm, predict movie ratings in the validation set as if they were unknown.

3) RMSE will be used to evaluate how close your predictions are to the true values in the validation set.

Data setup
```{r}

```



